spring:
  application:
    name: CarRentalSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/sso
    username: postgres
    password: $wuQ88hK
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.boot.autoconfigure: INFO


